package com.warehouse.dal.mapper;

import com.warehouse.dal.model.InventoryRecordDO;

public interface InventoryRecordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_record
     *
     * @mbg.generated
     */
    int insert(InventoryRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_record
     *
     * @mbg.generated
     */
    int insertSelective(InventoryRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_record
     *
     * @mbg.generated
     */
    InventoryRecordDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InventoryRecordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InventoryRecordDO record);
}