package com.warehouse.dal.mapper;

import com.warehouse.dal.model.ProductSKUDO;

public interface ProductSKUDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbg.generated
     */
    int insert(ProductSKUDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbg.generated
     */
    int insertSelective(ProductSKUDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbg.generated
     */
    ProductSKUDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductSKUDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductSKUDO record);
}