package com.warehouse.dal.mapper;

import com.warehouse.dal.model.ProductSkuDO;

public interface ProductSkuDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbg.generated
     */
    int insert(ProductSkuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbg.generated
     */
    int insertSelective(ProductSkuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbg.generated
     */
    ProductSkuDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductSkuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductSkuDO record);
}