server:
  port: 8088
# 数据源
spring:
  datasource:
    url: jdbc:mysql://10.8.107.234:3306/inventory?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: mysql_123456
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 300000
      pool-name: DateSourceHikariCP
      connection-test-query: SELECT 1
      connection-init-sql: set names utf8mb4;
mybatis:
  type-aliases-package: com.warehouse.dal.mapper
  mapper-locations: classpath*:sqlmap/**/*Mapper.xml
  config-location: classpath:mybatis-config.xml
