package com.warehouse.dal.model;

import java.io.Serializable;
import java.util.Date;

public class AudienceDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audience.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audience.audience_id
     *
     * @mbg.generated
     */
    private String audienceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audience.audience_name
     *
     * @mbg.generated
     */
    private String audienceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audience.audience_desc
     *
     * @mbg.generated
     */
    private String audienceDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audience.audience_expression
     *
     * @mbg.generated
     */
    private String audienceExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audience.is_delete
     *
     * @mbg.generated
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audience.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audience.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column audience.audience_content
     *
     * @mbg.generated
     */
    private String audienceContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table audience
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audience.id
     *
     * @return the value of audience.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audience.id
     *
     * @param id the value for audience.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audience.audience_id
     *
     * @return the value of audience.audience_id
     *
     * @mbg.generated
     */
    public String getAudienceId() {
        return audienceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audience.audience_id
     *
     * @param audienceId the value for audience.audience_id
     *
     * @mbg.generated
     */
    public void setAudienceId(String audienceId) {
        this.audienceId = audienceId == null ? null : audienceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audience.audience_name
     *
     * @return the value of audience.audience_name
     *
     * @mbg.generated
     */
    public String getAudienceName() {
        return audienceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audience.audience_name
     *
     * @param audienceName the value for audience.audience_name
     *
     * @mbg.generated
     */
    public void setAudienceName(String audienceName) {
        this.audienceName = audienceName == null ? null : audienceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audience.audience_desc
     *
     * @return the value of audience.audience_desc
     *
     * @mbg.generated
     */
    public String getAudienceDesc() {
        return audienceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audience.audience_desc
     *
     * @param audienceDesc the value for audience.audience_desc
     *
     * @mbg.generated
     */
    public void setAudienceDesc(String audienceDesc) {
        this.audienceDesc = audienceDesc == null ? null : audienceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audience.audience_expression
     *
     * @return the value of audience.audience_expression
     *
     * @mbg.generated
     */
    public String getAudienceExpression() {
        return audienceExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audience.audience_expression
     *
     * @param audienceExpression the value for audience.audience_expression
     *
     * @mbg.generated
     */
    public void setAudienceExpression(String audienceExpression) {
        this.audienceExpression = audienceExpression == null ? null : audienceExpression.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audience.is_delete
     *
     * @return the value of audience.is_delete
     *
     * @mbg.generated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audience.is_delete
     *
     * @param isDelete the value for audience.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audience.gmt_create
     *
     * @return the value of audience.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audience.gmt_create
     *
     * @param gmtCreate the value for audience.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audience.gmt_modified
     *
     * @return the value of audience.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audience.gmt_modified
     *
     * @param gmtModified the value for audience.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column audience.audience_content
     *
     * @return the value of audience.audience_content
     *
     * @mbg.generated
     */
    public String getAudienceContent() {
        return audienceContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column audience.audience_content
     *
     * @param audienceContent the value for audience.audience_content
     *
     * @mbg.generated
     */
    public void setAudienceContent(String audienceContent) {
        this.audienceContent = audienceContent == null ? null : audienceContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", audienceId=").append(audienceId);
        sb.append(", audienceName=").append(audienceName);
        sb.append(", audienceDesc=").append(audienceDesc);
        sb.append(", audienceExpression=").append(audienceExpression);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", audienceContent=").append(audienceContent);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AudienceDO other = (AudienceDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAudienceId() == null ? other.getAudienceId() == null : this.getAudienceId().equals(other.getAudienceId()))
            && (this.getAudienceName() == null ? other.getAudienceName() == null : this.getAudienceName().equals(other.getAudienceName()))
            && (this.getAudienceDesc() == null ? other.getAudienceDesc() == null : this.getAudienceDesc().equals(other.getAudienceDesc()))
            && (this.getAudienceExpression() == null ? other.getAudienceExpression() == null : this.getAudienceExpression().equals(other.getAudienceExpression()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()))
            && (this.getAudienceContent() == null ? other.getAudienceContent() == null : this.getAudienceContent().equals(other.getAudienceContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audience
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAudienceId() == null) ? 0 : getAudienceId().hashCode());
        result = prime * result + ((getAudienceName() == null) ? 0 : getAudienceName().hashCode());
        result = prime * result + ((getAudienceDesc() == null) ? 0 : getAudienceDesc().hashCode());
        result = prime * result + ((getAudienceExpression() == null) ? 0 : getAudienceExpression().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        result = prime * result + ((getAudienceContent() == null) ? 0 : getAudienceContent().hashCode());
        return result;
    }
}