package com.warehouse.dal.model;

import java.io.Serializable;
import java.util.Date;

public class InventoryDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.sku_id
     *
     * @mbg.generated
     */
    private Long skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.total_remaining
     *
     * @mbg.generated
     */
    private Integer totalRemaining;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.out_bound_times
     *
     * @mbg.generated
     */
    private Integer outBoundTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.out_bound
     *
     * @mbg.generated
     */
    private Integer outBound;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.in_bound_times
     *
     * @mbg.generated
     */
    private Integer inBoundTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.in_bound
     *
     * @mbg.generated
     */
    private Integer inBound;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.is_delete
     *
     * @mbg.generated
     */
    private Byte isDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inventory.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inventory
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.id
     *
     * @return the value of inventory.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.id
     *
     * @param id the value for inventory.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.product_id
     *
     * @return the value of inventory.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.product_id
     *
     * @param productId the value for inventory.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.sku_id
     *
     * @return the value of inventory.sku_id
     *
     * @mbg.generated
     */
    public Long getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.sku_id
     *
     * @param skuId the value for inventory.sku_id
     *
     * @mbg.generated
     */
    public void setSkuId(Long skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.unit
     *
     * @return the value of inventory.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.unit
     *
     * @param unit the value for inventory.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.total_remaining
     *
     * @return the value of inventory.total_remaining
     *
     * @mbg.generated
     */
    public Integer getTotalRemaining() {
        return totalRemaining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.total_remaining
     *
     * @param totalRemaining the value for inventory.total_remaining
     *
     * @mbg.generated
     */
    public void setTotalRemaining(Integer totalRemaining) {
        this.totalRemaining = totalRemaining;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.out_bound_times
     *
     * @return the value of inventory.out_bound_times
     *
     * @mbg.generated
     */
    public Integer getOutBoundTimes() {
        return outBoundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.out_bound_times
     *
     * @param outBoundTimes the value for inventory.out_bound_times
     *
     * @mbg.generated
     */
    public void setOutBoundTimes(Integer outBoundTimes) {
        this.outBoundTimes = outBoundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.out_bound
     *
     * @return the value of inventory.out_bound
     *
     * @mbg.generated
     */
    public Integer getOutBound() {
        return outBound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.out_bound
     *
     * @param outBound the value for inventory.out_bound
     *
     * @mbg.generated
     */
    public void setOutBound(Integer outBound) {
        this.outBound = outBound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.in_bound_times
     *
     * @return the value of inventory.in_bound_times
     *
     * @mbg.generated
     */
    public Integer getInBoundTimes() {
        return inBoundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.in_bound_times
     *
     * @param inBoundTimes the value for inventory.in_bound_times
     *
     * @mbg.generated
     */
    public void setInBoundTimes(Integer inBoundTimes) {
        this.inBoundTimes = inBoundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.in_bound
     *
     * @return the value of inventory.in_bound
     *
     * @mbg.generated
     */
    public Integer getInBound() {
        return inBound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.in_bound
     *
     * @param inBound the value for inventory.in_bound
     *
     * @mbg.generated
     */
    public void setInBound(Integer inBound) {
        this.inBound = inBound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.is_delete
     *
     * @return the value of inventory.is_delete
     *
     * @mbg.generated
     */
    public Byte getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.is_delete
     *
     * @param isDelete the value for inventory.is_delete
     *
     * @mbg.generated
     */
    public void setIsDelete(Byte isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.gmt_create
     *
     * @return the value of inventory.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.gmt_create
     *
     * @param gmtCreate the value for inventory.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inventory.gmt_modified
     *
     * @return the value of inventory.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inventory.gmt_modified
     *
     * @param gmtModified the value for inventory.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", productId=").append(productId);
        sb.append(", skuId=").append(skuId);
        sb.append(", unit=").append(unit);
        sb.append(", totalRemaining=").append(totalRemaining);
        sb.append(", outBoundTimes=").append(outBoundTimes);
        sb.append(", outBound=").append(outBound);
        sb.append(", inBoundTimes=").append(inBoundTimes);
        sb.append(", inBound=").append(inBound);
        sb.append(", isDelete=").append(isDelete);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        InventoryDO other = (InventoryDO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getSkuId() == null ? other.getSkuId() == null : this.getSkuId().equals(other.getSkuId()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getTotalRemaining() == null ? other.getTotalRemaining() == null : this.getTotalRemaining().equals(other.getTotalRemaining()))
            && (this.getOutBoundTimes() == null ? other.getOutBoundTimes() == null : this.getOutBoundTimes().equals(other.getOutBoundTimes()))
            && (this.getOutBound() == null ? other.getOutBound() == null : this.getOutBound().equals(other.getOutBound()))
            && (this.getInBoundTimes() == null ? other.getInBoundTimes() == null : this.getInBoundTimes().equals(other.getInBoundTimes()))
            && (this.getInBound() == null ? other.getInBound() == null : this.getInBound().equals(other.getInBound()))
            && (this.getIsDelete() == null ? other.getIsDelete() == null : this.getIsDelete().equals(other.getIsDelete()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtModified() == null ? other.getGmtModified() == null : this.getGmtModified().equals(other.getGmtModified()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inventory
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getSkuId() == null) ? 0 : getSkuId().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getTotalRemaining() == null) ? 0 : getTotalRemaining().hashCode());
        result = prime * result + ((getOutBoundTimes() == null) ? 0 : getOutBoundTimes().hashCode());
        result = prime * result + ((getOutBound() == null) ? 0 : getOutBound().hashCode());
        result = prime * result + ((getInBoundTimes() == null) ? 0 : getInBoundTimes().hashCode());
        result = prime * result + ((getInBound() == null) ? 0 : getInBound().hashCode());
        result = prime * result + ((getIsDelete() == null) ? 0 : getIsDelete().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtModified() == null) ? 0 : getGmtModified().hashCode());
        return result;
    }
}