package com.warehouse.dal.mapper.ext;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.warehouse.dal.model.InventoryDO;
import com.warehouse.dal.model.ext.ExtInventorySearchDO;

public interface ExtInventoryDOMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * inventory
     *
     * @mbg.generated
     */
    int insert(InventoryDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * inventory
     *
     * @mbg.generated
     */
    InventoryDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * inventory
     *
     * @mbg.generated
     */
    List<InventoryDO> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InventoryDO record);

    List<InventoryDO> selectAdminList(ExtInventorySearchDO searchDO);
}
