package com.warehouse.dal.mapper.ext;

import java.util.List;

import com.warehouse.dal.model.ProductSKUDO;

public interface ExtProductSKUDOMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product_sku
     *
     * @mbg.generated
     */
    int insert(ProductSKUDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product_sku
     *
     * @mbg.generated
     */
    ProductSKUDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product_sku
     *
     * @mbg.generated
     */
    List<ProductSKUDO> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * product_sku
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductSKUDO record);
}
